"use client";

import FormInput from "@/components/form/Input";
import SelectInput from "@/components/form/SelectInput";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import React from "react";
import { Controller, useForm } from "react-hook-form";
import type { CounselingNoteData, DisciplineIncidentData, StaffOption, StudentHealthRecordData, StudentOption } from "./wellbeingTypes";
import { staffLabel, studentLabel } from "./wellbeingTypes";

const severityOptions = ["Low", "Medium", "High", "Critical"].map((value) => ({ value, label: value }));
const disciplineStatuses = ["Open", "Under Review", "Resolved", "Archived"].map((value) => ({ value, label: value }));
const counselingStatuses = ["Open", "Follow Up", "Closed", "Archived"].map((value) => ({ value, label: value }));
const bloodGroups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"].map((value) => ({ value, label: value }));

type CommonProps<T> = {
    mode: "create" | "edit";
    initialData?: T;
    students: StudentOption[];
    staff?: StaffOption[];
    isOpen: boolean;
    isSubmitting?: boolean;
    onClose: () => void;
    onSubmit: (data: T) => void;
};

export function DisciplineIncidentForm({ mode, initialData, students, staff = [], isOpen, isSubmitting, onClose, onSubmit }: CommonProps<DisciplineIncidentData>) {
    const { control, handleSubmit, register, reset, formState: { errors } } = useForm<DisciplineIncidentData>({ defaultValues: initialData || { studentId: "", incidentDate: new Date().toISOString().slice(0, 10), category: "", severity: "Low", description: "", actionTaken: "", status: "Open" } });
    React.useEffect(() => { if (isOpen) reset(initialData || { studentId: "", incidentDate: new Date().toISOString().slice(0, 10), category: "", severity: "Low", description: "", actionTaken: "", status: "Open" }); }, [initialData, isOpen, reset]);
    return <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-[720px] bg-white rounded-xl p-0 shadow-lg border-none"><DialogHeader className="bg-slate-50 px-6 py-4 border-b border-slate-100 rounded-t-xl"><DialogTitle className="text-base font-bold text-slate-800">{mode === "create" ? "Add Discipline Incident" : "Edit Discipline Incident"}</DialogTitle></DialogHeader><form onSubmit={handleSubmit(onSubmit)} className="space-y-4 px-6 py-4"><Controller control={control} name="studentId" render={({ field }) => <SelectInput label="Student" searchable required showNoneOption={false} options={students.map((item) => ({ value: item.id, label: studentLabel(item) }))} value={field.value} onChange={field.onChange} />} /><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Controller control={control} name="incidentDate" render={({ field }) => <FormInput id="incidentDate" type="date" label="Incident Date" required value={field.value?.slice(0, 10)} onChange={field.onChange} />} /><Controller control={control} name="severity" render={({ field }) => <SelectInput label="Severity" showNoneOption={false} options={severityOptions} value={field.value} onChange={field.onChange} />} /><Controller control={control} name="status" render={({ field }) => <SelectInput label="Status" showNoneOption={false} options={disciplineStatuses} value={field.value} onChange={field.onChange} />} /></div><FormInput id="category" label="Category" required error={errors.category?.message} {...register("category", { required: "Category is required" })} /><FormInput id="description" label="Description" required error={errors.description?.message} {...register("description", { required: "Description is required" })} /><FormInput id="actionTaken" label="Action Taken" {...register("actionTaken")} /><Controller control={control} name="reportedById" render={({ field }) => <SelectInput label="Reported By" searchable options={staff.map((item) => ({ value: item.id, label: staffLabel(item) }))} value={field.value || ""} onChange={field.onChange} />} /><DialogFooter className="mt-6 flex flex-row gap-3 justify-end bg-slate-50 -mx-6 -mb-4 px-6 py-4 border-t border-slate-100 rounded-b-xl"><Button type="button" variant="outline" onClick={onClose} disabled={isSubmitting}>Cancel</Button><Button type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving..." : "Save"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function HealthRecordForm({ mode, initialData, students, isOpen, isSubmitting, onClose, onSubmit }: CommonProps<StudentHealthRecordData>) {
    const { control, handleSubmit, register, reset } = useForm<StudentHealthRecordData>({ defaultValues: initialData || { studentId: "", bloodGroup: "", allergies: "", medicalNotes: "", medications: "", emergencyContactName: "", emergencyContactPhone: "", emergencyContactRelation: "", doctorName: "", doctorPhone: "" } });
    React.useEffect(() => { if (isOpen) reset(initialData || { studentId: "", bloodGroup: "", allergies: "", medicalNotes: "", medications: "", emergencyContactName: "", emergencyContactPhone: "", emergencyContactRelation: "", doctorName: "", doctorPhone: "" }); }, [initialData, isOpen, reset]);
    return <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-[760px] bg-white rounded-xl p-0 shadow-lg border-none"><DialogHeader className="bg-slate-50 px-6 py-4 border-b border-slate-100 rounded-t-xl"><DialogTitle className="text-base font-bold text-slate-800">{mode === "create" ? "Create Health Profile" : "Edit Health Profile"}</DialogTitle></DialogHeader><form onSubmit={handleSubmit(onSubmit)} className="space-y-4 px-6 py-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Controller control={control} name="studentId" render={({ field }) => <SelectInput label="Student" searchable required showNoneOption={false} options={students.map((item) => ({ value: item.id, label: studentLabel(item) }))} value={field.value} onChange={field.onChange} />} /><Controller control={control} name="bloodGroup" render={({ field }) => <SelectInput label="Blood Group" options={bloodGroups} value={field.value || ""} onChange={field.onChange} />} /></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><FormInput id="allergies" label="Allergies" {...register("allergies")} /><FormInput id="medications" label="Medications" {...register("medications")} /></div><FormInput id="medicalNotes" label="Medical Notes" {...register("medicalNotes")} /><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><FormInput id="emergencyContactName" label="Emergency Contact" {...register("emergencyContactName")} /><FormInput id="emergencyContactPhone" label="Emergency Phone" {...register("emergencyContactPhone")} /><FormInput id="emergencyContactRelation" label="Relation" {...register("emergencyContactRelation")} /></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><FormInput id="doctorName" label="Doctor Name" {...register("doctorName")} /><FormInput id="doctorPhone" label="Doctor Phone" {...register("doctorPhone")} /></div><DialogFooter className="mt-6 flex flex-row gap-3 justify-end bg-slate-50 -mx-6 -mb-4 px-6 py-4 border-t border-slate-100 rounded-b-xl"><Button type="button" variant="outline" onClick={onClose} disabled={isSubmitting}>Cancel</Button><Button type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving..." : "Save"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function CounselingNoteForm({ mode, initialData, students, staff = [], isOpen, isSubmitting, onClose, onSubmit }: CommonProps<CounselingNoteData>) {
    const { control, handleSubmit, register, reset, formState: { errors } } = useForm<CounselingNoteData>({ defaultValues: initialData || { studentId: "", noteDate: new Date().toISOString().slice(0, 10), concernType: "", summary: "", followUpPlan: "", nextFollowUpDate: "", visibility: "Restricted", status: "Open" } });
    React.useEffect(() => { if (isOpen) reset(initialData || { studentId: "", noteDate: new Date().toISOString().slice(0, 10), concernType: "", summary: "", followUpPlan: "", nextFollowUpDate: "", visibility: "Restricted", status: "Open" }); }, [initialData, isOpen, reset]);
    return <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-[760px] bg-white rounded-xl p-0 shadow-lg border-none"><DialogHeader className="bg-slate-50 px-6 py-4 border-b border-slate-100 rounded-t-xl"><DialogTitle className="text-base font-bold text-slate-800">{mode === "create" ? "Add Counseling Note" : "Edit Counseling Note"}</DialogTitle></DialogHeader><form onSubmit={handleSubmit(onSubmit)} className="space-y-4 px-6 py-4"><Controller control={control} name="studentId" render={({ field }) => <SelectInput label="Student" searchable required showNoneOption={false} options={students.map((item) => ({ value: item.id, label: studentLabel(item) }))} value={field.value} onChange={field.onChange} />} /><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Controller control={control} name="noteDate" render={({ field }) => <FormInput id="noteDate" type="date" label="Note Date" required value={field.value?.slice(0, 10)} onChange={field.onChange} />} /><Controller control={control} name="status" render={({ field }) => <SelectInput label="Status" showNoneOption={false} options={counselingStatuses} value={field.value} onChange={field.onChange} />} /><Controller control={control} name="nextFollowUpDate" render={({ field }) => <FormInput id="nextFollowUpDate" type="date" label="Next Follow Up" value={field.value?.slice(0, 10) || ""} onChange={field.onChange} />} /></div><FormInput id="concernType" label="Concern Type" {...register("concernType")} /><FormInput id="summary" label="Private Summary" required error={errors.summary?.message} {...register("summary", { required: "Summary is required" })} /><FormInput id="followUpPlan" label="Follow Up Plan" {...register("followUpPlan")} /><Controller control={control} name="counselorId" render={({ field }) => <SelectInput label="Counselor" searchable options={staff.map((item) => ({ value: item.id, label: staffLabel(item) }))} value={field.value || ""} onChange={field.onChange} />} /><DialogFooter className="mt-6 flex flex-row gap-3 justify-end bg-slate-50 -mx-6 -mb-4 px-6 py-4 border-t border-slate-100 rounded-b-xl"><Button type="button" variant="outline" onClick={onClose} disabled={isSubmitting}>Cancel</Button><Button type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving..." : "Save"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
