"use client";

import FormInput from "@/components/form/Input";
import SelectInput from "@/components/form/SelectInput";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import React from "react";
import { Controller, useForm } from "react-hook-form";
import type { ApprovalData, ImportJobData, NotificationData } from "./operationTypes";

const jobStatuses = ["Queued", "Running", "Completed", "Failed", "Cancelled"].map((value) => ({ value, label: value }));
const notificationTypes = ["Info", "Success", "Warning", "Error"].map((value) => ({ value, label: value }));

export function ApprovalForm({ isOpen, isSubmitting, onClose, onSubmit }: { isOpen: boolean; isSubmitting?: boolean; onClose: () => void; onSubmit: (data: ApprovalData) => void }) {
    const { handleSubmit, register, reset, formState: { errors } } = useForm<ApprovalData>({ defaultValues: { title: "", module: "", entityType: "", entityId: "" } });
    React.useEffect(() => { if (isOpen) reset({ title: "", module: "", entityType: "", entityId: "" }); }, [isOpen, reset]);
    return <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-[560px] bg-white rounded-xl p-0 border-none"><DialogHeader className="bg-slate-50 px-6 py-4 border-b rounded-t-xl"><DialogTitle className="text-base font-bold">Create Approval Request</DialogTitle></DialogHeader><form onSubmit={handleSubmit(onSubmit)} className="space-y-4 px-6 py-4"><FormInput id="title" label="Title" required error={errors.title?.message} {...register("title", { required: "Title is required" })} /><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><FormInput id="module" label="Module" required error={errors.module?.message} {...register("module", { required: "Module is required" })} /><FormInput id="entityType" label="Entity Type" {...register("entityType")} /></div><FormInput id="entityId" label="Entity ID" {...register("entityId")} /><DialogFooter className="mt-6 flex flex-row gap-3 justify-end bg-slate-50 -mx-6 -mb-4 px-6 py-4 border-t rounded-b-xl"><Button type="button" variant="outline" onClick={onClose} disabled={isSubmitting}>Cancel</Button><Button type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving..." : "Save"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function ImportJobForm({ mode, initialData, isOpen, isSubmitting, onClose, onSubmit }: { mode: "create" | "edit"; initialData?: ImportJobData; isOpen: boolean; isSubmitting?: boolean; onClose: () => void; onSubmit: (data: ImportJobData) => void }) {
    const { control, handleSubmit, register, reset, formState: { errors } } = useForm<ImportJobData>({ defaultValues: initialData || { module: "", fileName: "", status: "Queued", totalRows: 0, processedRows: 0, successRows: 0, failedRows: 0 } });
    React.useEffect(() => { if (isOpen) reset(initialData || { module: "", fileName: "", status: "Queued", totalRows: 0, processedRows: 0, successRows: 0, failedRows: 0 }); }, [initialData, isOpen, reset]);
    return <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-[640px] bg-white rounded-xl p-0 border-none"><DialogHeader className="bg-slate-50 px-6 py-4 border-b rounded-t-xl"><DialogTitle className="text-base font-bold">{mode === "create" ? "Create Import Job" : "Update Import Job"}</DialogTitle></DialogHeader><form onSubmit={handleSubmit(onSubmit)} className="space-y-4 px-6 py-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><FormInput id="module" label="Module" required error={errors.module?.message} {...register("module", { required: "Module is required" })} /><FormInput id="fileName" label="File Name" {...register("fileName")} /></div><Controller control={control} name="status" render={({ field }) => <SelectInput label="Status" showNoneOption={false} options={jobStatuses} value={field.value} onChange={field.onChange} />} /><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><FormInput id="totalRows" label="Total" type="number" {...register("totalRows", { valueAsNumber: true })} /><FormInput id="processedRows" label="Processed" type="number" {...register("processedRows", { valueAsNumber: true })} /><FormInput id="successRows" label="Success" type="number" {...register("successRows", { valueAsNumber: true })} /><FormInput id="failedRows" label="Failed" type="number" {...register("failedRows", { valueAsNumber: true })} /></div><FormInput id="errorSummary" label="Error Summary" {...register("errorSummary")} /><DialogFooter className="mt-6 flex flex-row gap-3 justify-end bg-slate-50 -mx-6 -mb-4 px-6 py-4 border-t rounded-b-xl"><Button type="button" variant="outline" onClick={onClose} disabled={isSubmitting}>Cancel</Button><Button type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving..." : "Save"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function NotificationForm({ isOpen, isSubmitting, onClose, onSubmit }: { isOpen: boolean; isSubmitting?: boolean; onClose: () => void; onSubmit: (data: NotificationData) => void }) {
    const { control, handleSubmit, register, reset, formState: { errors } } = useForm<NotificationData>({ defaultValues: { title: "", body: "", type: "Info", actionUrl: "" } });
    React.useEffect(() => { if (isOpen) reset({ title: "", body: "", type: "Info", actionUrl: "" }); }, [isOpen, reset]);
    return <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-[560px] bg-white rounded-xl p-0 border-none"><DialogHeader className="bg-slate-50 px-6 py-4 border-b rounded-t-xl"><DialogTitle className="text-base font-bold">Create Notification</DialogTitle></DialogHeader><form onSubmit={handleSubmit(onSubmit)} className="space-y-4 px-6 py-4"><FormInput id="title" label="Title" required error={errors.title?.message} {...register("title", { required: "Title is required" })} /><FormInput id="body" label="Message" required error={errors.body?.message} {...register("body", { required: "Message is required" })} /><Controller control={control} name="type" render={({ field }) => <SelectInput label="Type" showNoneOption={false} options={notificationTypes} value={field.value} onChange={field.onChange} />} /><FormInput id="actionUrl" label="Action URL" {...register("actionUrl")} /><DialogFooter className="mt-6 flex flex-row gap-3 justify-end bg-slate-50 -mx-6 -mb-4 px-6 py-4 border-t rounded-b-xl"><Button type="button" variant="outline" onClick={onClose} disabled={isSubmitting}>Cancel</Button><Button type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving..." : "Save"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
